### ISSUE TITLE
Potential security issue in src/dealer.cpp: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/libzmq#1]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `src/dealer.cpp` 
Function: `write@pipe_t@zmq` 
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/dealer.cpp#L62
Code extract:

```cpp
        int rc = probe_msg.init ();
        errno_assert (rc == 0);

        rc = pipe_->write (&probe_msg); <------ HERE
        // zmq_assert (rc) is not applicable here, since it is not a bug.
        LIBZMQ_UNUSED (rc);
```

**How can I fix it?** 
Correct reference usage found in `src/xsub.cpp` at line `272`.
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/xsub.cpp#L272
Code extract:

```cpp
    errno_assert (rc == 0);

    //  Send it to the pipe.
    const bool sent = pipe->write (&msg); <------ HERE
    //  If we reached the SNDHWM, and thus cannot send the subscription, drop
    //  the subscription message instead. This matches the behaviour of
```

**Comment by siva-msft** [comment]
assignment fp
