### ISSUE TITLE
Potential security issue in src/socket_base.cpp: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/libzmq#3]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

7 instances of this defect were found in the following locations:
---
**Instance 1**
File : `src/socket_base.cpp` 
Function: `zmq_msg_init_size` 
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/socket_base.cpp#L1984
Code extract:

```cpp
                //  Send event and value in first frame
                const uint16_t event = static_cast<uint16_t> (event_);
                const uint32_t value = static_cast<uint32_t> (values_[0]);
                zmq_msg_init_size (&msg, sizeof (event) + sizeof (value)); <------ HERE
                uint8_t *data = static_cast<uint8_t *> (zmq_msg_data (&msg));
                //  Avoid dereferencing uint32_t on unaligned address
```

**How can I fix it?** 
Correct reference usage found in `src/zmq.cpp` at line `471`.
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/zmq.cpp#L471
Code extract:

```cpp
    zmq_msg_t msg;

    for (size_t i = 0; i < count_; ++i) {
        rc = zmq_msg_init_size (&msg, a_[i].iov_len); <------ HERE
        if (rc != 0) {
            rc = -1;
```

---
**Instance 2**
File : `src/socket_base.cpp` 
Function: `zmq_msg_init_size` 
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/socket_base.cpp#L1995
Code extract:

```cpp
                  endpoint_uri_pair_.identifier ();

                //  Send address in second frame
                zmq_msg_init_size (&msg, endpoint_uri.size ()); <------ HERE
                memcpy (zmq_msg_data (&msg), endpoint_uri.c_str (),
                        endpoint_uri.size ());
```

**How can I fix it?** 
Correct reference usage found in `src/zmq.cpp` at line `471`.
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/zmq.cpp#L471
Code extract:

```cpp
    zmq_msg_t msg;

    for (size_t i = 0; i < count_; ++i) {
        rc = zmq_msg_init_size (&msg, a_[i].iov_len); <------ HERE
        if (rc != 0) {
            rc = -1;
```

---
**Instance 3**
File : `src/socket_base.cpp` 
Function: `zmq_msg_init_size` 
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/socket_base.cpp#L2002
Code extract:

```cpp
            } break;
            case 2: {
                //  Send event in first frame (64bit unsigned)
                zmq_msg_init_size (&msg, sizeof (event_)); <------ HERE
                memcpy (zmq_msg_data (&msg), &event_, sizeof (event_));
                zmq_msg_send (&msg, _monitor_socket, ZMQ_SNDMORE);
```

**How can I fix it?** 
Correct reference usage found in `src/zmq.cpp` at line `471`.
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/zmq.cpp#L471
Code extract:

```cpp
    zmq_msg_t msg;

    for (size_t i = 0; i < count_; ++i) {
        rc = zmq_msg_init_size (&msg, a_[i].iov_len); <------ HERE
        if (rc != 0) {
            rc = -1;
```

---
**Instance 4**
File : `src/socket_base.cpp` 
Function: `zmq_msg_init_size` 
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/socket_base.cpp#L2007
Code extract:

```cpp
                zmq_msg_send (&msg, _monitor_socket, ZMQ_SNDMORE);

                //  Send number of values that will follow in second frame
                zmq_msg_init_size (&msg, sizeof (values_count_)); <------ HERE
                memcpy (zmq_msg_data (&msg), &values_count_,
                        sizeof (values_count_));
```

**How can I fix it?** 
Correct reference usage found in `src/zmq.cpp` at line `471`.
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/zmq.cpp#L471
Code extract:

```cpp
    zmq_msg_t msg;

    for (size_t i = 0; i < count_; ++i) {
        rc = zmq_msg_init_size (&msg, a_[i].iov_len); <------ HERE
        if (rc != 0) {
            rc = -1;
```

---
**Instance 5**
File : `src/socket_base.cpp` 
Function: `zmq_msg_init_size` 
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/socket_base.cpp#L2014
Code extract:

```cpp

                //  Send values in third-Nth frames (64bit unsigned)
                for (uint64_t i = 0; i < values_count_; ++i) {
                    zmq_msg_init_size (&msg, sizeof (values_[i])); <------ HERE
                    memcpy (zmq_msg_data (&msg), &values_[i],
                            sizeof (values_[i]));
```

**How can I fix it?** 
Correct reference usage found in `src/zmq.cpp` at line `471`.
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/zmq.cpp#L471
Code extract:

```cpp
    zmq_msg_t msg;

    for (size_t i = 0; i < count_; ++i) {
        rc = zmq_msg_init_size (&msg, a_[i].iov_len); <------ HERE
        if (rc != 0) {
            rc = -1;
```

---
**Instance 6**
File : `src/socket_base.cpp` 
Function: `zmq_msg_init_size` 
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/socket_base.cpp#L2021
Code extract:

```cpp
                }

                //  Send local endpoint URI in second-to-last frame (string)
                zmq_msg_init_size (&msg, endpoint_uri_pair_.local.size ()); <------ HERE
                memcpy (zmq_msg_data (&msg), endpoint_uri_pair_.local.c_str (),
                        endpoint_uri_pair_.local.size ());
```

**How can I fix it?** 
Correct reference usage found in `src/zmq.cpp` at line `471`.
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/zmq.cpp#L471
Code extract:

```cpp
    zmq_msg_t msg;

    for (size_t i = 0; i < count_; ++i) {
        rc = zmq_msg_init_size (&msg, a_[i].iov_len); <------ HERE
        if (rc != 0) {
            rc = -1;
```

---
**Instance 7**
File : `src/socket_base.cpp` 
Function: `zmq_msg_init_size` 
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/socket_base.cpp#L2027
Code extract:

```cpp
                zmq_msg_send (&msg, _monitor_socket, ZMQ_SNDMORE);

                //  Send remote endpoint URI in last frame (string)
                zmq_msg_init_size (&msg, endpoint_uri_pair_.remote.size ()); <------ HERE
                memcpy (zmq_msg_data (&msg), endpoint_uri_pair_.remote.c_str (),
                        endpoint_uri_pair_.remote.size ());
```

**How can I fix it?** 
Correct reference usage found in `src/zmq.cpp` at line `471`.
https://github.com/sagpant/libzmq/blob/522abc73766364d176d7f97ba544cf38fd3f79bb/src/zmq.cpp#L471
Code extract:

```cpp
    zmq_msg_t msg;

    for (size_t i = 0; i < count_; ++i) {
        rc = zmq_msg_init_size (&msg, a_[i].iov_len); <------ HERE
        if (rc != 0) {
            rc = -1;
```

**Comment by siva-msft** [comment]
likely bug. lgtm
